### PR TITLE
Bump to kotlin 1.8.10

### PR DESCRIPTION
**Pull request by evanchooly**
I have built and tested this locally on my ksp project (https://github.com/MorphiaOrg/critter) and it works quite well on kotlin 1.8.10.  I could really use a 1.5 release so I can use this is my other projects already on 1.8.

### CODE REVIEW

**Comment by fxshlein** [comment]
Hi! Thank you very much for the PR! I quickly made #89, because Dependabot seems to not handle maven properties in versions well. I'll release 1.5 now!

**Comment by fxshlein** [comment]
And I made you a co-author of https://github.com/Dyescape/kotlin-maven-symbol-processing/commit/ac66964ddf222da9789015ca982fe226f6505021, that way you're not robbed of your contributor status in this repo 😉

**Comment by evanchooly** [comment]
> Hi! Thank you very much for the PR! I quickly made #89, because Dependabot seems to not handle maven properties in versions well. I'll release 1.5 now!

Strange. I wonder what broke. I use properties all the time.  But no matter, so long as things work in the end.

**Comment by fxshlein** [comment]
It wouldn't create PRs like this one anymore, since it couldn't actually figure out that it has to actually update the property instead of the `<version>` tag: https://github.com/Dyescape/kotlin-maven-symbol-processing/pull/92/files

Did they fix that/add that? We don't have that many repos on GitHub, but it would still be nice to switch back to using properties if it works now.

**Comment by evanchooly** [comment]
I use this approach on all of mine.  It was definitely more useful.when updates were manual but even with automatic updates, it's nice to be able to see what versions are in use and the diffs are smaller on updates.

**Pull request closed without merging**
